max_trans_vel: 0.8
min_trans_vel: 0.05

max_vel_x: 0.3
min_vel_x: 0.05

max_vel_y: 0
min_vel_y: 0

max_rot_vel: 0.3
min_rot_vel: 0.0

acc_lim_theta: 1.0
acc_lim_x: 1
acc_lim_y: 0
acc_lim_trans: 1.0

yaw_goal_tolerance: 0.15
xy_goal_tolerance: 0.2
dwa: false

sim_time: 2.0

vx_samples: 5
vy_samples: 0
vtheta_samples: 15

meter_scoring: true
penalize_negative_x: false

oscillation_reset_dist: 0.05

publish_traj_pc: true
publish_cost_grid_pc: true
global_frame_id: map

sim_granularity: 0.025
goal_distance_bias: 2.0
path_distance_bias: 10.0
occdist_scale: 0.3
stop_time_buffer: 0.8

scaling_speed: 0.25
max_scaling_factor: 0.2

rot_stopped_vel: 0.01
trans_stopped_vel: 0.01
